# Docker Junior Course Definition
COURSE_ID = "docker-junior-ops"
COURSE_TITLE = "Docker Junior Level"
COURSE_DESCRIPTION = "Master container mechanics, image building optimization, local networks, volumes, and multi-container environment management for DevOps, SRE, and backend workflows."

CURRICULUM_DATA = [
    {
        "id": 1,
        "title": "Module 1: Core Container Architecture & Command Line Operations",
        "theory": """
### Virtual Machines vs. Containers
Understanding how containers differ from traditional Virtual Machines (VMs) is fundamental to designing reliable infrastructure:
*   **Virtual Machines:** Run on physical hardware via a hypervisor. Each VM includes its own guest operating system, device drivers, and virtualized hardware. This setup incurs significant resource overhead (memory, CPU, and storage footprints) and slow startup phases.
*   **Containers:** Share the host operating system's kernel. They run as isolated processes in user space using Linux kernel primitives: namespaces (for visibility isolation) and control groups/cgroups (for physical resource limits). This architecture results in near-zero virtualization overhead and near-instant start times.

### Images vs. Containers
*   **Docker Image:** A read-only template built from layered filesystems (UnionFS). It packages system dependencies, libraries, binaries, and configurations. Images are immutable.
*   **Docker Container:** A running instance of a Docker image. When a container starts, Docker adds a thin, writeable container layer on top of the read-only image layers. Any runtime data, modifications, or log generations are handled in this writeable layer unless persisted externally.
        """,
        "commands": """
### Command Reference

These essential CLI commands form the bedrock of daily operational workflows and container troubleshooting:

* `docker run [OPTIONS] [IMAGE]`  
  Initializes and launches a container from a specified target image.  
  - `-d`: Detaches execution (runs container in the background).  
  - `--name [NAME]`: Assigns an explicit name to avoid random autogenerated identifiers.  
  - `--restart [POLICY]`: Specifies behavior (e.g., `always`, `on-failure`) if the container exits.  
* `docker ps`  
  Lists active running containers. Append `-a` to show stopped and failed instances.  
* `docker logs [CONTAINER]`  
  Retrieves standard output (stdout) and standard error (stderr) streams from a target container.  
  - `-f`: Follows/streams log output in real time.  
* `docker exec -it [CONTAINER] [COMMAND]`  
  Executes an interactive process (e.g., an interactive shell) inside a running container context.  
* `docker inspect [CONTAINER/IMAGE]`  
  Outputs detailed, low-level JSON configuration and state metadata of a target object.  
* `docker stats`  
  Displays a live stream of container resource usage statistics (CPU, memory, network I/O).  
* `docker cp [SOURCE] [DESTINATION]`  
  Copies files or folders between a container's filesystem and the host filesystem.  
* `docker stop [CONTAINER]`  
  Sends a SIGTERM signal, followed by a SIGKILL after a grace period, to stop a container.  
* `docker rm [CONTAINER]`  
  Removes a stopped container from local storage.  
* `docker system prune`  
  Reclaims disk space by purging stopped containers, unused networks, and dangling build caches.
        """,
        "examples": """
### Real-World Examples

#### Example 1: Starting and Tracking a Detached Background Worker
*   **Situation:** You need to spin up a background worker container that processes tasks and verify it continues to run reliably.
*   **Action:** Launch a detached container with a specified name and inspect its operational status:
    ```bash
    # Run a busybox task processor in the background
    docker run -d --name task-processor busybox sh -c "while true; do echo 'Processing worker queue...'; sleep 5; done"

    # Confirm its execution status
    docker ps -f name=task-processor
    ```

#### Example 2: Copying Application Configuration Files Dynamically
*   **Situation:** You need to pull a config file out of a running server container to verify environment values without stopping the process.
*   **Action:** Use the `docker cp` interface to extract the targeted asset:
    ```bash
    # Spin up an nginx container
    docker run -d --name test-web nginx:alpine

    # Copy the default configuration file from the container to your local working directory
    docker cp test-web:/etc/nginx/nginx.conf ./local-nginx.conf
    ```

#### Example 3: Auditing Live Resource Consumption Metrics
*   **Situation:** You are diagnosing a memory leak inside an application process running within a local container.
*   **Action:** Track memory and CPU usage on the host terminal in real time:
    ```bash
    # Stream live resource metrics
    docker stats --format "table {{.Name}}\\t{{.CPUPerc}}\\t{{.MemUsage}}\\t{{.NetIO}}"
    ```

#### Example 4: Extracting Network Configurations from Container Metadata
*   **Situation:** You need to obtain the internal IP address of a container to test local network routing.
*   **Action:** Query the container metadata and parse the network details using go-templates:
    ```bash
    # Inspect and filter specifically for the container IP address
    docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' task-processor
    ```

#### Example 5: Recovering Storage by Pruning Unused Resources
*   **Situation:** Your local development host has run out of disk space due to cumulative testing runs.
*   **Action:** Run a safe cleanup routine to purge abandoned container structures:
    ```bash
    # Clear stopped containers and dangling images to reclaim disk blocks
    docker system prune -f
    ```
        """,
        "exercise": """
### Hands-On Labs

#### Lab 1: Managing Container Lifecycles
*   **Objective:** Practice launching, monitoring, and cleaning up a target container.
*   **Tasks:**
    1. Run a detached container named `dns-probe` using `alpine` that continually pings `8.8.8.8`.
    2. Retrieve the last 10 lines of the container's logs to verify successful pings.
    3. Stop the container and confirm it is no longer listed in active processes, but remains in the inactive list.
    4. Delete the container and verify it is completely purged from storage.
    5. Attempt to use the same name `dns-probe` for a new container to ensure no naming conflicts remain.

#### Lab 2: Real-time Log Monitoring & Signal Handling
*   **Objective:** Learn how to read live terminal outputs and handle clean termination.
*   **Tasks:**
    1. Start a container using `python:3.10-slim` that prints numbers 1 to 100 with a 1-second delay.
    2. Attach to the logs in stream mode (`-f`) and watch the live sequence output.
    3. Open a second terminal window and stop the container using `docker stop`.
    4. Inspect the exit code of the stopped container to verify if it exited with code `0` or a non-zero signal.
    5. Remove the container to clean up.

#### Lab 3: Troubleshooting Runtime Environments
*   **Objective:** Debug runtime issues by entering an active container environment.
*   **Tasks:**
    1. Run a detached background `nginx` container.
    2. Execute an interactive shell session inside the running container context.
    3. Navigate to the `/etc/nginx` folder, locate the main configuration file, and read its contents from within the container.
    4. Run `ps aux` inside the container to see the processes running inside the isolated namespace.
    5. Exit the container shell session and verify the container continues to run in the background.

#### Lab 4: Runtime Configuration Audits
*   **Objective:** Extract internal metadata to verify state parameters.
*   **Tasks:**
    1. Start a container named `audit-target` running `redis:alpine`.
    2. Run a `docker inspect` query to find its state configuration and determine its `Running` status (True/False).
    3. Find the exact path where the container's standard output log file is saved on the host.
    4. Locate the volume configuration and check if any host directories are mounted inside.
    5. Clean up the container by stopping and removing it.

#### Lab 5: Container Resource Profiling under Load
*   **Objective:** Track the impact of workload execution on container resource constraints.
*   **Tasks:**
    1. Run a helper container that performs a system stress routine (e.g., executing a computation loop).
    2. Open your terminal metrics viewer using `docker stats` and observe the CPU/Memory percentages.
    3. Record how the numbers fluctuate under active computational load.
    4. Stop the container to bring the host CPU utilization back to idle.
    5. Clean up any remaining container resources.
        """,
        "insight": """
### Interview Q&A

#### Q1: What is the primary difference between how a Virtual Machine and a Container share host resources?
*   **Answer:** A VM packages a guest operating system and virtualizes hardware using a hypervisor, which translates instructions to the physical CPU. A container shares the host system's kernel directly, isolating processes through kernel namespaces and managing resource limits via cgroups. This results in minimal CPU and memory overhead compared to a VM.

#### Q2: What is the functional difference between `docker stop` and `docker kill`?
*   **Answer:** `docker stop` sends a `SIGTERM` signal to the primary container process (PID 1), allowing it to clean up open files, finish active requests, and shut down gracefully. If it doesn't shut down within a grace period (default 10s), it sends `SIGKILL`. `docker kill` bypasses the graceful phase and immediately sends `SIGKILL` to terminate the process instantly.

#### Q3: Where is data stored inside a container, and what happens to it when the container is deleted?
*   **Answer:** Data is written to a thin, writeable container layer that sits on top of the immutable image layers. This writeable layer is tightly coupled to the container's lifecycle. When the container is deleted (`docker rm`), its writeable layer is permanently destroyed, and any data stored inside it is lost unless persistent storage (volumes/bind mounts) was utilized.

#### Q4: What is the purpose of Linux namespaces and cgroups in the context of Docker?
*   **Answer:** They are the underlying Linux kernel technologies that make containers possible. **Namespaces** provide process-level isolation, hiding resources (like processes, network interfaces, filesystems, and IPC) from other containers. **Control groups (cgroups)** enforce resource governance, restricting how much CPU, memory, network bandwidth, or disk I/O a container can consume.

#### Q5: Why is it considered an operational risk to run containers as the `root` user by default?
*   **Answer:** If a container runs as `root` and a security vulnerability allows a process escape, the attacker could gain root privileges on the host kernel. Restricting the container process to run as a non-privileged user (using the `USER` directive) minimizes the blast radius of a runtime exploit.

### CKA/Docker Focus
Be ready to quickly inspect and locate a container's internal IP address, read active log outputs, and manage lifecycle commands without leaving dangling resources on the host machine.
        """
    },
    {
        "id": 2,
        "title": "Module 2: Containerization, Layer Optimization, & Service Exposing",
        "theory": """
### Build Mechanics and Caching
A Dockerfile contains instructions executed sequentially to construct an image. Each directive creates a read-only filesystem layer.
*   **Layer Caching:** To speed up builds, Docker checks if previous image builds have already run a command on the same base layers. If no files have changed, Docker reuses the cached layer.
*   **Cache Invalidation:** If any step changes (e.g., copying modified source code), that layer and all subsequent layers must be rebuilt from scratch. For applications using dependencies (like Python libraries in `requirements.txt` or Node packages in `package.json`), you can install dependencies before copying your main codebase. This ensures dependency installation layers remain cached unless package manifests are updated.

### Service Exposing and Port Mapping
Applications inside a container bind to internal ports (e.g., `8000`, `5000`). To access these services from your browser or external monitoring systems:
*   **Port Mapping (`-p host:container`):** Bridges the host network port to the isolated container port.
*   **EXPOSE Directive:** Documents which ports the application listens on. It does not map ports to the host; it acts as an operational contract between the application developer and the infrastructure manager.
        """,
        "commands": """
### Command Reference

* `docker build -t [TAG_NAME]:[VERSION] [PATH]`  
  Compiles a Dockerfile located at the path into an executable image with a specific tag.  
* `docker run -p [HOST_PORT]:[CONTAINER_PORT] [IMAGE]`  
  Runs a container and binds the host port to the internal container port.  
* `docker history [IMAGE]`  
  Displays the size, composition, and creation commands of each filesystem layer in an image.  
* `docker tag [SOURCE_IMAGE] [TARGET_IMAGE]`  
  Creates a new tag referencing an existing local image, often used for versioning or registry naming.  
* `docker save -o [FILE.tar] [IMAGE]` / `docker load -i [FILE.tar]`  
  Exports an image to a tarball archive, or imports an image archive back into local Docker storage.
        """,
        "examples": """
### Real-World Examples

#### Example 1: Creating an Optimized Dockerfile for a Python Application
*   **Situation:** You want to package a Python backend while optimizing build times and minimizing layer rebuilding during daily development code updates.
*   **Action:** Write a Dockerfile that copies only dependency lockfiles before running the package installer:
    ```dockerfile
    FROM python:3.10-slim

    WORKDIR /app

    # Install dependencies first to leverage the cache
    COPY requirements.txt .
    RUN pip install --no-cache-dir -r requirements.txt

    # Copy the remaining application source code
    COPY . .

    EXPOSE 8000
    CMD ["python", "main.py"]
    ```

#### Example 2: Mapping a Port to Prevent Host Conflicts
*   **Situation:** You are running multiple instances of an API on a single test server, but they all run on port `8000` internally.
*   **Action:** Run containers and map their internal ports to unique, non-overlapping host ports:
    ```bash
    # Run instance 1 on host port 8081
    docker run -d -p 8081:8000 --name api-instance-1 backend-api:v1.0

    # Run instance 2 on host port 8082
    docker run -d -p 8082:8000 --name api-instance-2 backend-api:v1.0
    ```

#### Example 3: Auditing Layer Sizes to Reduce Footprint
*   **Situation:** You need to audit an image to find which step is contributing the most to a large image size.
*   **Action:** Run `docker history` to list each layer size and find the bottleneck:
    ```bash
    docker history backend-api:v1.0
    ```

#### Example 4: Creating a Multi-Stage Dockerfile for Production
*   **Situation:** You want to compile a binary or install build tools, but exclude those heavy tools from the final runtime image to keep it lightweight.
*   **Action:** Use multi-stage builds to copy only compiled artifacts into a clean, minimal base image:
    ```dockerfile
    # Stage 1: Build and compile
    FROM python:3.10-slim AS builder
    WORKDIR /build
    COPY requirements.txt .
    RUN pip install --no-cache-dir --user -r requirements.txt

    # Stage 2: Clean runtime stage
    FROM python:3.10-slim
    WORKDIR /app
    # Copy only installed libraries from the builder stage
    COPY --from=builder /root/.local /root/.local
    COPY . .
    ENV PATH=/root/.local/bin:$PATH
    EXPOSE 8000
    CMD ["python", "main.py"]
    ```

#### Example 5: Injecting Build-Time Variables
*   **Situation:** You need to embed a git commit hash or version tag inside the image metadata at build time.
*   **Action:** Use the `ARG` directive in the Dockerfile and pass build arguments via the command line:
    ```dockerfile
    FROM alpine
    ARG BUILD_VERSION
    ENV APP_VERSION=$BUILD_VERSION
    CMD ["sh", "-c", "echo Running version $APP_VERSION"]
    ```
    ```bash
    # Build passing the argument
    docker build --build-arg BUILD_VERSION=v1.4.2 -t versioned-app .
    ```
        """,
        "exercise": """
### Hands-On Labs

#### Lab 1: Building a Cached Python Application Image
*   **Objective:** Understand how Docker's layer cache works by building and updating an image.
*   **Tasks:**
    1. Create a workspace directory containing a simple `requirements.txt` listing `requests` or `flask`.
    2. Write a Dockerfile that copies `requirements.txt` and runs `pip install` before copying the rest of your files.
    3. Build the image: `docker build -t cache-demo:v1 .`.
    4. Make a small text change to your app code and rebuild as `cache-demo:v2`.
    5. Verify in the output logs that the package installation step bypassed downloading and used the cache.

#### Lab 2: Crafting a Multi-Stage Build
*   **Objective:** Optimize image sizes and keep build tools out of your final image.
*   **Tasks:**
    1. Write a multi-stage Dockerfile containing a compilation stage (builder) and a clean production stage.
    2. Build the image using `docker build -t multi-stage:latest .`.
    3. Compare the storage size of this image against a single-stage version using `docker images`.
    4. Confirm the runtime image contains only necessary runtime assets.

#### Lab 3: Port Forwarding and Verification
*   **Objective:** Expose internal container applications to host networks.
*   **Tasks:**
    1. Build an application image that hosts a web interface on port `5000`.
    2. Start the container mapping host port `9090` to container port `5000`.
    3. Run a network request from your host machine (`curl http://localhost:9090`) to verify connectivity.
    4. Stop the container and verify that connections to host port `9090` are closed.

#### Lab 4: Tracking and Debugging Image History
*   **Objective:** Identify which commands add unnecessary storage overhead to your images.
*   **Tasks:**
    1. Build an image containing multiple package installations and raw data copies.
    2. Run `docker history` to analyze the layer creation process.
    3. Identify layers that contain redundant system packages.
    4. Refactor your Dockerfile to chain commands (`RUN apt-get update && apt-get install -y ... && rm -rf /var/lib/apt/lists/*`) to reduce layer sizes.
    5. Rebuild the image and verify the size reduction.

#### Lab 5: Archiving and Sharing Images Manually
*   **Objective:** Share images between isolated host systems without a registry.
*   **Tasks:**
    1. Build a local image named `archive-app:v1.0`.
    2. Export the image to a tarball using `docker save -o archive-app.tar archive-app:v1.0`.
    3. Delete the local image from your Docker system.
    4. Restore the image from the tarball using `docker load -i archive-app.tar`.
    5. Confirm the image is once again available in your `docker images` list.
        """,
        "insight": """
### Interview Q&A

#### Q1: Why do we separate the dependency installation step from the source code copying step in a Dockerfile?
*   **Answer:** Docker builds images layer-by-layer and caches each layer. If any files change in a copy operation, the cache for that layer and all subsequent layers is invalidated. By copying only dependency list files first, the slow package installation step remains cached unless dependencies actually change, saving significant build time during code modifications.

#### Q2: What is the operational difference between `CMD` and `ENTRYPOINT` in a Dockerfile?
*   **Answer:** `ENTRYPOINT` defines the executable binary that always runs when the container starts. `CMD` provides default arguments or parameters to that executable. Users can easily override the `CMD` values by appending arguments to the `docker run` command, whereas overriding the `ENTRYPOINT` requires an explicit `--entrypoint` flag.

#### Q3: How do build-time arguments (`ARG`) differ from runtime environment variables (`ENV`)?
*   **Answer:** `ARG` variables are only available during the image build process (e.g., specifying version tags or compiler flags) and are not accessible once the container starts running. `ENV` variables persist within the image metadata and are available to the application process at runtime.

#### Q4: How do multi-stage builds help improve container security in production?
*   **Answer:** Multi-stage builds allow you to use development dependencies, compilers, and debugging utilities in a builder stage, and copy only the compiled binaries or runtime files into a slim production stage. This reduces the image's footprint and minimizes the attack surface by ensuring no unnecessary shell utilities or compilers are present in production.

#### Q5: Why is using the `latest` image tag discouraged in production deployments?
*   **Answer:** The `latest` tag is mutable and dynamic. When a base image or application dependencies are updated, the registry updates `latest` to point to the new image. If a system pulls the image during auto-healing or scaling, it might fetch an untested version, leading to inconsistent application states and hard-to-debug failures across your infrastructure.

### CKA/Docker Focus
Be comfortable managing image size optimizations, troubleshooting build cache invalidation issues, and diagnosing port mapping mismatches in live environments.
        """
    },
    {
        "id": 3,
        "title": "Module 3: Multi-Container Orchestration, Network Abstraction, & Volumes",
        "theory": """
### Docker Compose Mechanics
Managing multiple individual containers via shell commands becomes error-prone. **Docker Compose** allows you to define and manage a multi-container stack (e.g., an application, database, and cache) using a single declarative configuration file (`docker-compose.yml`).

### Container Isolation & DNS Networking
By default, Docker Compose sets up a single, private network for your stack. Each service container on this network can communicate with other services using their service names as DNS hostnames (e.g., connecting a web service to a database using `db:5432` rather than hardcoding IP addresses).

### Volume Abstractions & Persistence
Containers are ephemeral; their data disappears once they are deleted. To manage persistent states or share files with the host, Docker provides:
*   **Named Volumes:** Docker-managed disk storage isolated from host directory structures. Ideal for databases and long-term state.
*   **Bind Mounts:** Directly maps a path on the host machine to a path inside the container. Ideal for local development, allowing real-time code changes on your host to reflect instantly inside the container without rebuilding.
        """,
        "commands": """
### Command Reference

These commands should be executed from the directory containing your `docker-compose.yml` file:

* `docker compose up`  
  Configures, builds, creates, and starts all services outlined in the Compose file.  
  - `-d`: Launches the services in background (detached) mode.  
* `docker compose down`  
  Stops and cleans up containers, networks, and internal resources defined by the stack.  
  - `-v`: Purges associated named volumes alongside the containers.  
* `docker compose ps`  
  Displays the current runtime status of containers managed by the local Compose context.  
* `docker compose logs [SERVICE]`  
  Streams aggregated logs from all services, or filters logs for a single target service.  
* `docker compose exec [SERVICE] [COMMAND]`  
  Runs an interactive terminal command inside a running service container.
        """,
        "examples": """
### Real-World Examples

#### Example 1: Multi-Container Configuration (Web + Cache)
*   **Situation:** You need to launch a local development stack containing a Python application and a Redis cache on an isolated network.
*   **Action:** Create a `docker-compose.yml` defining the two services:
    ```yaml
    version: "3.8"

    services:
      web:
        build: .
        ports:
          - "8080:8000"
        environment:
          - REDIS_HOST=cache-service
        depends_on:
          - cache-service

      cache-service:
        image: "redis:alpine"
    ```

#### Example 2: Configuring Hot-Reloading using a Bind Mount
*   **Situation:** You want local application code changes to immediately sync to a running container without manually restarting or rebuilding.
*   **Action:** Use a bind mount mapping your current host directory to the container workspace:
    ```yaml
    version: "3.8"

    services:
      web:
        build: .
        ports:
          - "8000:8000"
        volumes:
          - .:/app
    ```

#### Example 3: Externalizing Secrets using Environment Variables
*   **Situation:** You need to configure credentials securely without hardcoding secrets in your configuration files.
*   **Action:** Define credentials in a `.env` file and reference them in your Compose file:
    ```env
    # Contents of local .env file
    DB_USER=ops_admin
    DB_PASS=vault_secret_pass
    ```
    ```yaml
    # Snippet inside docker-compose.yml
    services:
      db:
        image: postgres:alpine
        environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASS}
    ```

#### Example 4: Persisting Database State using Named Volumes
*   **Situation:** You need to ensure database tables and configurations are not lost when restarting or updating database containers.
*   **Action:** Declare a named volume and mount it to the database data directory:
    ```yaml
    version: "3.8"

    services:
      postgres-db:
        image: postgres:alpine
        environment:
          POSTGRES_PASSWORD: secret
        volumes:
          - db_data:/var/lib/postgresql/data

    volumes:
      db_data:
    ```

#### Example 5: Sequencing Startup Order with Health Checks
*   **Situation:** A web service crashes on startup because it tries to connect to the database before the database is ready to accept connections.
*   **Action:** Define startup dependencies using `depends_on` and service health checks:
    ```yaml
    version: "3.8"

    services:
      web:
        build: .
        ports:
          - "8000:8000"
        depends_on:
          db:
            condition: service_healthy

      db:
        image: postgres:alpine
        environment:
          POSTGRES_PASSWORD: secret
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 5
    ```
        """,
        "exercise": """
### Hands-On Labs

#### Lab 1: Deploying a Multi-Service Stack
*   **Objective:** Declare and manage multiple interconnected services.
*   **Tasks:**
    1. Create a `docker-compose.yml` file containing a backend web service and an isolated caching server.
    2. Start the stack in background mode: `docker compose up -d`.
    3. Verify that both containers are running using `docker compose ps`.
    4. View aggregated service startup logs using `docker compose logs`.
    5. Spin down the stack and verify all created containers and custom networks are removed.

#### Lab 2: Hot-Reloading local files via Bind Mounts
*   **Objective:** Keep code and container environments synchronized during local development.
*   **Tasks:**
    1. Set up a basic Python web application.
    2. Define a Compose service mapping your local directory to `/app` inside the container using a bind mount.
    3. Start your services.
    4. Modify a message string inside your host-side Python file and save it.
    5. Query your application container and confirm the updates are reflected instantly without a rebuild.

#### Lab 3: Decoupling Secrets via Environment Profiles
*   **Objective:** Pass dynamic database configurations into a running container environment safely.
*   **Tasks:**
    1. Create a `.env` file declaring database credentials.
    2. Reference these values inside a `docker-compose.yml` service definition.
    3. Bring up the environment and run `docker compose exec db env` to verify the environment variables were passed successfully.
    4. Change a value inside `.env` and restart the stack using `docker compose up -d`.
    5. Confirm the updated credentials were applied correctly inside the container.

#### Lab 4: Inter-Container DNS Verification
*   **Objective:** Verify automatic DNS-based service discovery between containers on a shared network.
*   **Tasks:**
    1. Define two services (`web` and `api`) in a `docker-compose.yml` file.
    2. Start the stack.
    3. Execute an interactive shell inside the `web` container: `docker compose exec web sh`.
    4. Ping the `api` container using its service name: `ping api`.
    5. Confirm that the DNS successfully resolves the service name to the `api` container's internal IP address.

#### Lab 5: Volume Persistence Audits
*   **Objective:** Verify that database records persist across container restarts.
*   **Tasks:**
    1. Create a database service in Compose and mount its data to a named volume.
    2. Start the service, log into the database shell, and create a test table with sample records.
    3. Stop and delete the container stack using `docker compose down`. Do not use the `-v` flag.
    4. Recreate the stack using `docker compose up -d`.
    5. Log back into the database and verify that your test table and sample records are still intact.
        """,
        "insight": """
### Interview Q&A

#### Q1: What is the primary difference between a Bind Mount and a Named Volume?
*   **Answer:** A bind mount maps a user-specified absolute path on the host machine to a directory inside the container, making it useful for local code development. A named volume is managed entirely by Docker within its storage directory (e.g., `/var/lib/docker/volumes/`). This makes named volumes more secure, easier to manage, and less dependent on host-specific directory paths.

#### Q2: How does Docker Compose resolve hostnames between isolated container services?
*   **Answer:** Docker Compose automatically creates a user-defined bridge network when you start a stack. This network features an embedded DNS server that resolves service names to their corresponding container IP addresses, allowing containers to safely communicate using readable hostnames instead of static IPs.

#### Q3: What is the limitation of the `depends_on` parameter, and how can you ensure a database is ready before your app connects?
*   **Answer:** By default, `depends_on` only tracks whether the dependent container has started, not whether the application inside it is ready to accept connections. To ensure a database is ready, you should define a `healthcheck` on the database service and use `depends_on` with a `service_healthy` condition.

#### Q4: What happens to persistent volumes when you run the `docker compose down` command?
*   **Answer:** Running `docker compose down` stops and removes containers and networks, but leaves named volumes untouched on the disk to prevent data loss. To permanently delete the associated volumes alongside your containers, you must run `docker compose down -v`.

#### Q5: How can you manage different environment settings (e.g., development vs. production) using Docker Compose?
*   **Answer:** You can use environment files (like `.env`) to swap configuration values across environments, or use multiple Compose files (e.g., `docker-compose.yml` and `docker-compose.override.yml`). Docker Compose automatically merges override files, allowing you to easily adjust ports, volumes, and logging parameters for different environments.

### CKA/Docker Focus
Understand how to define clean, multi-container configurations. Know how to implement health checks, use environment variables, and manage volumes to prevent data loss.
        """
    }
]